### ISSUE TITLE
API v3 still used in manage_gitlab_project.py?

### ISSUE THREAD

**Issue by nicocvn** [samrocketman/gitlab-mirrors#106]
I am currently using the development branch, and it seems that as of 73bd66e2e566eb557a455032e2666e2bca6bec85 the gitlab API v3 is still used.

I was getting this error trying to add a mirror:

```
gitmirror@git-box:~/gitlab-mirrors$ ./add_mirror.sh --git --project-name XXX --mirror XXX
Resolving gitlab remote.
/home/gitmirror/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 138, in <module>
    if needs_transfer(gitlab_user, gitlab_namespace, found_project):
  File "lib/manage_gitlab_project.py", line 124, in needs_transfer
    if type(project.namespace) == gitlab.v3.objects.Group:
AttributeError: 'module' object has no attribute 'v3'
There was an unknown issue with manage_gitlab_project.py
```
I simply changed v3 to v4 on line 124 and I was then able to add a mirror. Not sure if the issue is deeper but I could not find any other occurrences of v3 in the script. Also, in my config.sh I am specifying gitlab api v4.

Can submit a merge request if needed but first I would like to be sure that this is indeed the root cause of the issue.

**Comment by samrocketman** [comment]
Just on master.  I need to release from develop branch.

**Comment by samrocketman** [comment]
Hmm go for it.  I see what you mean now.

**Comment by samrocketman** [comment]
0.6.0 released which uses v4 GitLab API.

**Comment by Klowner** [comment]
Hey, just a heads up. https://github.com/samrocketman/gitlab-mirrors/blob/dd28d50faf46a2744c49b90bfda8b521b79afcd6/lib/manage_gitlab_project.py#L124 appears to still use `gitlab.v3` from `python-gitlab` which appears to have been removed in the `1.5.0` release.

**Comment by samrocketman** [comment]
Might be time to simply use raw REST.  The 3rd party libs don’t always react well and tend to be overkill for some specific needs of the project.

**Comment by samrocketman** [comment]
@kadimgh pull requests are welcome to fix it.  There’s no good reason I haven’t fixed it.  I spread myself thin across many projects and haven’t prioritized time to fix and test it.
