### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ssl_verify'

### ISSUE THREAD

**Issue by XelionIO** [samrocketman/gitlab-mirrors#113]
I've followed all the instructions, but got this error when trying to setup a github mirror :

`gitmirror@system:~/backup$ ./add_mirror.sh --git --project-name github-gitlab-mirrors --mirror https://github.com/samrocketman/gitlab-mirrors.git
Resolving gitlab remote.
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 50, in <module>
    git=gitlab.Gitlab(gitlab_url,token_secret,ssl_verify=True,api_version=gitlab_api_version)
TypeError: __init__() got an unexpected keyword argument 'ssl_verify'
There was an unknown issue with manage_gitlab_project.py`

I'm running the latest version of gitlab and gitlab-mirrors 0.6.1

**Comment by samrocketman** [comment]
Odd, I’ll have to try to replicate.

**Comment by XelionIO** [comment]
It's me, i've forgot to install the python requirements with :

`pip install -r requirement.exe`
