### ISSUE TITLE
support for gitlab 7

### ISSUE THREAD

**Issue by logicminds** [samrocketman/gitlab-mirrors#60]
The requirements say gitlab 6, can you specify if gitlab 7 works too?

**Comment by logicminds** [comment]
https://github.com/samrocketman/gitlab-mirrors/blob/master/docs/prerequisites.md

**Comment by samrocketman** [comment]
I found a possible issue with GitLab 7.6.2.  After some preliminary testing I've determined it is likely an upstream bug in `python-gitlab3`.  I have filed the issue under https://github.com/alexvh/python-gitlab3/issues/19.

**Comment by samrocketman** [comment]
False alarm.  I didn't follow my own instructions.  I did not make the gitmirror user an admin of gitlab.

**Comment by samrocketman** [comment]
I just tested with 7.6.2 and it appears to be good.

**Comment by logicminds** [comment]
Use my puppet code to do it for you.

**Comment by samrocketman** [comment]
Does it set up GitLab too?

**Comment by logicminds** [comment]
No, but there is puppet code for that too.

https://forge.puppetlabs.com/tags/gitlab
