### ISSUE TITLE
does not appear to be a git repository

### ISSUE THREAD

**Issue by logicminds** [samrocketman/gitlab-mirrors#61]
I just tried this on latest gitlab 7.x and there appears to be a major issue when pushing the mirror to the gitlab remote end.  Not sure what I am doing wrong.
Might this be happening because upon new project creation the git repo is empty?  Attached is a pic of the empty gitlab repo.

```shell
gitmirror@linux:~/repositories/github-mirrors/easy_type$ git push gitlab
fatal: 'github-mirrors/easy_type.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
gitmirror@linux:~/repositories/github-mirrors/easy_type$ git remote -v
gitlab	git@10.0.1.54:github-mirrors/easy_type.git (fetch)
gitlab	git@10.0.1.54:github-mirrors/easy_type.git (push)
origin	https://github.com/hajee/easy_type.git (fetch)
origin	https://github.com/hajee/easy_type.git (push)

gitmirror@linux:~/repositories/github-mirrors/easy_type$ git push -u gitlab
fatal: 'github-mirrors/easy_type.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

![screen shot 2015-01-06 at 11 04 41 pm](https://cloud.githubusercontent.com/assets/563900/5642054/9381ea36-95f8-11e4-98e7-89190fbe27f5.png)

**Comment by logicminds** [comment]
GitLab 7.6.1 0286222

**Comment by samrocketman** [comment]
The error:
```
Please make sure you have the correct access rights
and the repository exists.
```
Is key.

From the gitmirror user:
```
ssh git@10.0.1.54
```

If you SSH and it says Hello user then your credentials are set up correctly.  If not then you need to correct that.

**Comment by logicminds** [comment]
It may be just my system.  I am using the latest bitnami VM and the path to git is not available in a non-interactive shell (fixed with symlinks) but I fear there may be something else going on too.  Going to try against a non bitnami VM.  

also, ssh works find on the system.  I'll double check permissions issue as well.

**Comment by logicminds** [comment]
Looks like its just my system.

**Comment by samrocketman** [comment]
Fair enough.  Thanks for reporting back.
