### ISSUE TITLE
Upload ssh key script

### ISSUE THREAD

**Issue by samrocketman** [samrocketman/gitlab-mirrors#65]
Makes provisioning easier.  See #62.

**Comment by logicminds** [comment]
Did you get around to adding this feature?

**Comment by samrocketman** [comment]
No; I've been focusing on other areas of development in my spare time (maintaining the [Slack Jenkins plugin][1]; [repository secrets][2]; and [Jervis][3]).  I also maintain the [build infrastructure for the GIMP project][4].  My spare time is fairly booked and those projects don't include my full-time day job.  It's not something I'll be contributing any time soon, likely.

[1]: https://github.com/jenkinsci/slack-plugin
[2]: https://github.com/samrocketman/repository-secrets
[3]: https://github.com/samrocketman/jervis
[4]: https://build.gimp.org/

**Comment by samrocketman** [comment]
This effort is better put towards a ruby rewrite.  ref link #63.
