### ISSUE TITLE
How can I mirror issues,wikis and merger requests?

### ISSUE THREAD

**Issue by ijyun** [samrocketman/gitlab-mirrors#71]
I want to mirror my repo,not only files and commit but also issues,wikis and merge requests?How can I get this?
thanks

**Comment by samrocketman** [comment]
I take it you mean mirror those from github or another gitlab instance.

* gitlab-mirrors is not designed to mirror issues and merge requests from the UI.  You could write a script that interacts with the APIs for you source and destination.
* For mirroring the wiki you can pass the --no-create option to the add_mirror.sh script.  All Gitlab/github wikis are just git repositories.  The wikis are in project.wiki.git as opposed to project.git.
* if you want to mirror the code of pull requests or merge requests you can use git ls-remote to view the references.  I believe in GitHub they live in refs/pull/...

**Comment by ijyun** [comment]
@samrocketman I'll try what you say, thank you so much!

**Comment by informatimago** [comment]
Well, currently, it's possible to export and import issues thru CSV files. So you can export issues to a CSV file from one repository collection, and import the CSV file into another repository collection.
