### ISSUE TITLE
Query and Suggestion for SVN

### ISSUE THREAD

**Issue by TigerWolf** [samrocketman/gitlab-mirrors#74]
I am currently using gitlab-mirrors and its working great after a couple of tweaks. Thanks for all your hard work. 

One thing I noticed is that it does not create all the branches in SVN and push them to gitlab. This appears is a symptom of `git svn` as it does not check out all the branches after cloning. 

I have modified the script to use svn2git (https://github.com/nirvdrum/svn2git) - I was wondering if a pull request of adding this in would be appreciated. I understand adding 2 dependencies (ruby and svn2git) may not be desired.

**Comment by samrocketman** [comment]
Pull requests are welcome and if it improves mirroring I'm not against it.  Please review the contributing doc in the root of the repo.
