### ISSUE TITLE
error with GitLab 7.12.2 

### ISSUE THREAD

**Issue by logicminds** [samrocketman/gitlab-mirrors#76]
Switched to community edition and now receive this error

-bash-4.1$ /home/gitmirror/gitlab-mirrors/add_mirror.sh --git --project-name pe_puppetserver_gem --mirror https://github.com/puppetlabs/puppetlabs-pe_puppetserver_gem.git
Resolving gitlab remote.
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 109, in <module>
    found_project=createproject(project_name)
  File "lib/manage_gitlab_project.py", line 98, in createproject
    new_project=git.group(found_group.id).transfer_project(new_project.id)
AttributeError: 'bool' object has no attribute 'id'
There was an unknown issue with manage_gitlab_project.py

**Comment by logicminds** [comment]
fixed in #78

**Comment by samrocketman** [comment]
Just released v0.5.2 which is certified with GitLab 8.1.4.  `master` reflects the latest stable release.
