### ISSUE TITLE
Login credentials?

### ISSUE THREAD

**Issue by Norcoen** [samrocketman/gitlab-mirrors#81]
Is it possible to put your login credentials in the config somewhere to automaticly mirror protected repositories?
You can create the mirror on commandline supplying your credentials 2 times, but updates will obviously fail.

Kind regards,
Frank

**Comment by samrocketman** [comment]
The bash scripts simple use git commands.  So you can do anything that git supports.  Including:

* [Use the git credential helper store](http://git-scm.com/docs/git-credential-store)
* Include the username and password as part of the HTTP url for basic HTTP auth.
* Use SSH to clone with an SSH private key (RECOMMENDED).
