### ISSUE TITLE
Compatible with Gitlab 8

### ISSUE THREAD

**Issue by tomcashman** [samrocketman/gitlab-mirrors#86]
Hi,

I'm wondering if this is compatible with Gitlab 8?

**Comment by logicminds** [comment]
works for me on 8.1

**Comment by samrocketman** [comment]
Keep in mind @logicminds is referring to the `development` branch.  It's been over a year since I've made a stable release but `development` is pretty well tested by others and seems to work.  (primarily because I haven't used GitLab in over a year, though that's going to change soon)

**Comment by logicminds** [comment]
@samrocketman maybe its time to merge dev to master and tag a new release

**Comment by samrocketman** [comment]
Not a bad idea.  I should spin up a docker container with GitLab and test it so I can personally validate it works.  I've done that in the past (though I'm also okay with your testing since I'm sure you've been running off of the development branch for a while now).  I've mostly been focused on other open source projects so this one hasn't seen much love.

**Comment by logicminds** [comment]
I have been using the dev branch in production and use not only with gitlab-ce 7.13-8.1 but also gitlab.com and have not had any issues.

**Comment by pescobar** [comment]
having a new tested release supporting 8.x would be nice. I am also interested in using gitlab-mirrors with gitlab 8.x

**Comment by mawi001** [comment]
+1

**Comment by logicminds** [comment]
@samrocketman I have noticed many of the issues deal with https://github.com/samrocketman/gitlab-mirrors/issues/66 so I think it would be wise the merge this into master as this would eliminate most of the current issues.

**Comment by samrocketman** [comment]
I will, I'm spread really thin at the moment but I'll try to set some time aside this weekend to work on this and releasing to `master`.

**Comment by samrocketman** [comment]
Just released v0.5.2 which is certified with GitLab 8.1.4.  `master` reflects the latest stable release.
