### ISSUE TITLE
Does gitlab-mirrors work both ways?

### ISSUE THREAD

**Issue by d33tah** [samrocketman/gitlab-mirrors#87]
I set up a Github repository that I used to test gitlab-mirrors. I pushed a commit into this and then set up a mirror on my gitlab instance. The Github repository got imported, but when I pushed another commit into the Gitlab repo, it didn't get pushed back to Github. Is this normal behavior?

**Comment by samrocketman** [comment]
Yes, this is normal behavior.  It is meant to be a read only mirror (i.e. One-way).  For two-way mirroring it would require something more robust than what gitlab-mirrors provides.  There's no plans to change this.
