### ISSUE TITLE
InsecureRequestWarning

### ISSUE THREAD

**Issue by cdenneen** [samrocketman/gitlab-mirrors#88]
```
/home/gitmirror/gitlab-mirrors/add_mirror.sh --git --project-name puppet-staging --mirror https://github.com/nanliu/puppet-staging.git
Resolving gitlab remote.
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 109, in <module>
    found_project=createproject(project_name)
  File "lib/manage_gitlab_project.py", line 95, in createproject
    new_project=git.add_project(pname,description=description,**project_options)
  File "/usr/lib/python2.7/site-packages/gitlab3/__init__.py", line 184, in fn
    data = parent._post(api._uq_url, data=kwargs)
  File "/usr/lib/python2.7/site-packages/gitlab3/__init__.py", line 418, in _post
    return self._request(requests.post, api_url, addl_keys, data)
  File "/usr/lib/python2.7/site-packages/gitlab3/__init__.py", line 435, in _request
    self._check_status_code(r.status_code, url, data)
  File "/usr/lib/python2.7/site-packages/gitlab3/__init__.py", line 411, in _check_status_code
    raise self._code_to_exc[status_code](msg)
gitlab3.exceptions.MissingRequiredAttribute: URL: https://gitlab.domain.loc/api/v3/projects, Data: {'wall_enabled': 'false', 'snippets_enabled': 'false', 'merge_requests_enabled': 'false', 'name': 'puppet-staging', 'issues_enabled': 'false', 'wiki_enabled': 'false', 'public': 'true', 'description': 'Mirror of https://github.com/nanliu/puppet-staging.git'}
There was an unknown issue with manage_gitlab_project.py
```

Based on that I've tried to do an update of Python OpenSSL bindings as suggested but no luck:

```
pip install --upgrade requests[security]
```

Trying to figure out where this issue is if it's here or python-gitlab which you are calling?

**Comment by logicminds** [comment]
The main issue is that your gitlab server is using self signed certificates or the certificate is invalid. I would suggest you get a trusted cert and put on your gitlab server to remove the issue.  Another way around this is to include your self signed ca cert in your cert bundle for requests python api, but I don't know how to do that. 

See: http://webdesign.about.com/od/ssl/tp/cheapest-ssl-certificates.htm

**Comment by samrocketman** [comment]
If I recall from an email communication you said you were using an IP address to connect, correct?  SSL verification typically happens with a FQDN so you'll either have to A) get a FQDN and use SSL to verify or B) disable SSL verification in `config.sh`.

In addition to @logicminds suggestion about cheap SSL certificates I also list options for maintaining an internal certificate authority: https://github.com/samrocketman/my_internal_ca

**Comment by cdenneen** [comment]
@logicminds it's not a self signed by an internal AD CA which sadly Python doesn't know about. Need to figure out how to do this. 
This is one of my pet peeves with Linux not having a central store that all apps try to use. /etc/pki/tls/certs is used by certain apps but git needs to be told to look there. Then this doesn't work for other apps like ruby or Python. 
Wonder how @samrocketman myCA is handling this across these different apps wanting to do their own thing.

**Comment by samrocketman** [comment]
There's only a couple of places where system certificates are stored.  There's `/etc/ssl` which is usually a symlink to pki.  There's also the NSS store which stores certificates separately.  Those are the two primary certificate stores.  If you have an application which is using something other than those then it typically comes with options for using a specific certificate store.  In that case, since you've generated your own CA Certificate you use that for the verification.  I've yet to find any trouble doing that.

**Comment by cdenneen** [comment]
My point is the apps like git, Python or Ruby can be made to look anywhere
but don't search there by default. For example if I download our CA Root
Chain and place it in the certs directory it's not good enough I have to
explicitly tell git to use that Dir for sslca.

Also since you added branch option to your module, does it support
references too or just branch names? Now that Sam merged to master I can
switch back from development but was just curious for future reference.

**Comment by samrocketman** [comment]
> my point is...

Typically most apps use OpenSSL default paths or NSS for certificates.  Git does so your point is incorrect.  It works for me.

**Comment by cdenneen** [comment]
I'm actually going to retry this but seems just putting chain in certs directory isn't enough and you have to add hash to ca-bundle (which sadly periodically gets overwritten by updates, which is the problem I'm describing). On windows or mac certificates update all the time and don't require having to re-add to certificate store. If you have another way that doesn't require updating ca-bundle periodically with internal ca chain, to work with git, curl, etc, I'd be interested.

**Comment by samrocketman** [comment]
Depends on your distro.  For instance, Ubuntu is what I primarily use as a Desktop OS.  [There's instructions on safely installing root CA certificates](http://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate).  I typically use RHEL 6/CentOS 6 as a server OS and there's instructions for [safely adding to that as well](http://kb.kerio.com/product/kerio-connect/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html).  One can google a number of search terms and get the desired result:

* `nss add ca certificates` (for software using NSS db as a certificate store)
* `ubuntu add ca certificates`
* `centos add ca certificates`

To name a few.

**Comment by samrocketman** [comment]
Also, if you install the curl-devel package you can use `curl-config --ca` to get the typical path for your OS.  If it's blank (like on Mac) then use `curl-config --configure` to see what build options.  On Mac curl uses keychain for CA certs.

**Comment by samrocketman** [comment]
I'm going to close this issue since there doesn't appear to be a clear resolution path and there hasn't been any activity on it.

If you still encounter this bug.  Please feel free to open a new issue and link to this issue as related.
