### ISSUE TITLE
Type Error: list indices must be integers, not str

### ISSUE THREAD

**Issue by meldavis** [samrocketman/gitlab-mirrors#91]
When creating a mirror for a GitHub https:// based repo, I get the following error: 
```
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:793: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Creating new project r-plugin
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 105, in <module>
    found_project=createproject(project_name)
  File "lib/manage_gitlab_project.py", line 78, in createproject
    git.add_project(pname,description=description,**project_options)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3/__init__.py", line 185, in fn
    ret = api(parent, data)
  File "/usr/local/lib/python2.7/dist-packages/gitlab3/__init__.py", line 312, in __init__
    setattr(self, '_id', json_data[self._key_name])
TypeError: list indices must be integers, not str
There was an unknown issue with manage_gitlab_project.py
```
Any idea on how I can fix it?  Thanks!

**Comment by logicminds** [comment]
see #88

**Comment by meldavis** [comment]
I'm not sure this is the same problem.  For one, the error message on the next to last line (above) is different.   My error is "TypeError: list indices",  #88 error is gitlab3.exceptions.MissingRequiredAttribute

Also, I have set in gitlab-mirrors/config.sh,    ssl-verify=false

For my gitlab server, I am using a server certificate that was signed by a local CA, The local CA is installed in /etc/ssl/certs and appears in /etc/ssl/certs/ca-certificates.crt

Would you have any other suggestions?

**Comment by meldavis** [comment]
Sorry for wasting your time.    The problem was in my git-mirror configuration.   When I changed the gitlab server over from http:// to https://, I failed to change the url in the git-mirrors/config.yml.

Again, very sorry.  Love your product.  Thanks for sharing.

**Comment by samrocketman** [comment]
Glad you figured it out.
