### ISSUE TITLE
Unable to add new repo

### ISSUE THREAD

**Issue by nstires** [samrocketman/gitlab-mirrors#94]
Ran through a fresh install, using gitlab-ce-8.1.3 on Amazon Linux 2015.09.

When I execute:
`./add_mirror.sh --git --project-name zzzz --mirror git@bitbucket.org:acme/zzzz.git`

I get back:
```
Resolving gitlab remote.
Traceback (most recent call last):
  File "lib/manage_gitlab_project.py", line 105, in <module>
    found_project=createproject(project_name)
  File "lib/manage_gitlab_project.py", line 72, in createproject
    'namespace_id': git.find_group(name=gitlab_namespace).id,
AttributeError: 'NoneType' object has no attribute 'id'
There was an unknown issue with manage_gitlab_project.py
```

The group is Mirrors, under the user gitmirror, per the install guide. The ~/privatetoken is set up as well.

**Comment by samrocketman** [comment]
Have you created the `Mirror` group in GitLab first?  That's a manual step.
