### ISSUE TITLE
Asking for git@fqdn's password

### ISSUE THREAD

**Issue by tjskrish** [samrocketman/gitlab-mirrors#95]
I followed the steps given in the documentation. A project is being created in GitLab under the group specified. But then, immediately after "Checking the mirror into gitlab" it asks for password for git user. Not sure how to go about this. Any idea? The admin user I am using is root.
```
Creating mirror from <Gitolite link> 
Initialized empty Git repository in /root/repositories/Mirrors/test5/ 
Adding gitlab remote to project. 
Checking the mirror into gitlab. 
git@<FQDN>'s password:

**Comment by logicminds** [comment]
You need to setup your ssh keys and token.

**Comment by tjskrish** [comment]
I did create an id_rsa key

**Comment by logicminds** [comment]
You need to add the public key to the gitlab user's account that the gitmirror user runs under.

**Comment by logicminds** [comment]
The token is required in order to call the gitlab API

**Comment by tjskrish** [comment]
Yup i copied the private_token from gitlab to the location specified in the document.
But now i'm getting a new error, i changed the password for git user on gitlab host and entered that password when prompted. Now, i'm getting this error:

'''
Creating mirror from <Gitolite Link>
Initialized empty Git repository in /root/repositories/Mirrors/test5/
Adding gitlab remote to project.
Checking the mirror into gitlab.
git@FQDN's password: 
fatal: 'Mirrors/test5.git' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
'''

**Comment by logicminds** [comment]
That usually means that user does not have access to that repo.

**Comment by tjskrish** [comment]
I modified the config file, like, gitlab_user = "root" .. I dont understand why it is asking for git user's password.. hmm

**Comment by tjskrish** [comment]
HEYY !! It worked.. I just had to add the SHH public key in gitlab.. I missed that totally !
