### ISSUE TITLE
Repos only get cloned kind. Not a Mirror which shows on gitlab

### ISSUE THREAD

**Issue by hsitaa** [samrocketman/gitlab-mirrors#96]
Hi,

Gitmirror I can get repos in a folder named repository, But nothing on Gitlab UI of Mirror Server.

Repos only get cloned kind. Not a Mirror which shows on gitlab. Is there any step i am missing or this feature is not present ?

**Comment by samrocketman** [comment]
GitLab does not support mirrors.  I wrote these set of shell scripts because of that.  I also recommend ensuring that the projects which are mirrored are read only for anyone except for the account pushing.

These scripts update the description of the project stating that it's a mirror.

**Comment by logicminds** [comment]
Gitlab does support mirror now as of 8.3?  I uses background workers to mirror from just about any kind of git VCS host.  However, there are cases where these scripts are still useful.  

  * behind a firewall or no internet on the gitlab system
  * bulk importing of many projects

**Comment by samrocketman** [comment]
Ah, I was not aware; thanks for the update.  I haven't used GitLab in a couple years now.  I'll have to look at it again :-)

**Comment by hsitaa** [comment]
@logicminds 
Hi, gitlab Community edition Still don't have, its only in enterprise edition.  Please correct me if i am wrong.

**Comment by samrocketman** [comment]
Since this appears to be an enterprise-only feature I don't see it being implemented any time soon.  However, if someone would like to implement this so it supports EE and CE without issues then I'd be open to merging the change.

For now, I'll just close this. Contributions are still welcome down the line.
