### ISSUE TITLE
Feature Request: Sync only specific branch of project

### ISSUE THREAD

**Issue by tiferrei** [samrocketman/gitlab-mirrors#97]
Hello there, 
Usually when I work on an open source project I keep the master branch up-to-date with the Source and add my features on a separate developer branch. I have been doing this by setting up another remote for the source on the git config, and setting the master to fetch from source and push to gitlab, I was thinking if this could be automated via this tool?

Thank you,
Tiago

**Comment by samrocketman** [comment]
Hello Tiago,
I think for your use case it might be overkill to set up scripts to sync master from an upstream project.  Something like this is already easily done just by slightly adjusting your git settings.  Here's an example.

```bash
git clone [project]
cd projectfolder
git remote add upstream [project]
git config --add remote.origin.push '+refs/remotes/upstream/master:refs/heads/master'
git fech --all
git checkout upstream/master -b myfeature
#make some changes on myfeature branch
git push origin -u myfeature
```

Notes:
* The remote name `upstream` is arbitrary.
* `git fetch --all` is needed to fetch all remotes.  e.g. `origin` and `upstream`.
* When you push any branch to `origin` it should update `origin/master` based on `upstream/master`.

See `git help push` and read about `refspec`.

I'd have to do some testing myself but hypothetically the git configuration should work.  I haven't tested the above commands so try it out on something unimportant first.

**Comment by tiferrei** [comment]
Yes, that's what I currently do for all my projects, but it kind of sucks when I branch from master to create a feature, and then realise I forgot to pull the master so it was behind upstream. :/

**Comment by samrocketman** [comment]
You'll face that same problem with your origin remote master.  Just create branches from the remote.  e.g.

```bash
git fetch --all
git checkout upstream/master -b myfeature
#or more generically
gut checkout [remote]/[branch] -b [new branch]
```
